// ============================================================
// manifest-globals.d.ts — types for the WIKI_MANIFEST global that
// static/generated/manifest.js (generated by build.ts) defines before
// nav.js runs. Type-only mirror of lib/types.ts manifest shapes
// (browser scripts compile without module imports).
// ============================================================

interface WikiManifestPageRecord {
  path: string;
  domain: string;
  category: string;
  section: string | null;
  role: "home" | "hub" | "overview" | "deep-dive" | "page";
  title: string;
  nav: string;
  topics: string[];
  blurb: string;
  difficulty: "E" | "M" | "H" | null;
  problemNumber: number | null;
  order: number | null;
}

interface WikiManifestSection {
  identifier: string;
  label: string;
  hubPath: string | null;
  pagePaths: string[];
}

interface WikiManifestCategory {
  identifier: string;
  label: string;
  layout: "sections" | "flat";
  hubPath: string | null;
  sections: WikiManifestSection[];
  pagePaths: string[];
}

interface WikiManifestDomain {
  identifier: string;
  label: string;
  categories: WikiManifestCategory[];
}

interface WikiManifestData {
  siteTitle: string;
  domains: WikiManifestDomain[];
  pages: Record<string, WikiManifestPageRecord>;
}

declare const WIKI_MANIFEST: WikiManifestData;
