// ============================================================
// pages.js — THE single registry of wiki pages.
// RULE: only finished, existing files are listed here — the hub
// and nav must never show anything that isn't done.
//
// To add a page: drop the HTML file in the right subfolder
// and add ONE entry here. Top nav and the hub index update
// automatically. Nothing else to edit.
//
// Fields:
//   cat        "theory" | "walkthrough" | "tips"
//   path       relative to the wiki/ root
//   nav        short label for the top nav bar
//   title      full title for hub cards
//   topics     short topic list shown on the hub card
//   difficulty "E" | "M" | "H"  (walkthroughs only)
//   blurb      one line for the hub card description
//
// ORDERING RULE — walkthroughs:
//   Always insert new walkthrough entries in ascending LC number order.
//   The nav bar renders entries in the order they appear here — a
//   misordered entry produces a misordered nav. No exceptions.
// ============================================================
const WIKI_PAGES = [
  {
    cat: "theory",
    path: "theory/arrays/index.html",
    nav: "Arrays & Hashing",
    title: "Arrays & Hashing",
    topics: ["Arrays", "Hash Map", "Two Pointers", "Sliding Window"],
    blurb: "Arrays & Hashing hub — overview, hash map, two pointers, and sliding window masterfiles.",
  },
  {
    cat: "theory",
    path: "theory/intervals/intervals_overview_master.html",
    nav: "Intervals",
    title: "Intervals",
    topics: ["Arrays", "Sorting", "Sweep"],
    blurb: "Sort-then-sweep interval technique — merge, overlap, insert, gap-find, and split/handoff coverage variants.",
  },
  {
    cat: "theory",
    path: "theory/strings/index.html",
    nav: "Strings & Simulation",
    title: "Strings & Simulation",
    topics: ["Strings", "Simulation", "Stack", "Parsing"],
    blurb: "Strings & Simulation hub — overview, text-formatting/simulation, and string-parsing masterfiles.",
  },
  {
    cat: "theory",
    path: "theory/stacks/stack_overview_master.html",
    nav: "Stacks",
    title: "Stacks",
    topics: ["Stack", "LIFO", "Parsing", "Graphs", "Design"],
    blurb: "Stack overview — three canonical skeletons: push-openers/pop-match (bracket validation, expression eval), push-containers/pop-and-attach (nested structure parse), and explicit DFS. Swift toolbox, pitfalls, and routing diagram.",
  },
  {
    cat: "theory",
    path: "theory/design/index.html",
    nav: "Object & System Design",
    title: "Object & System Design",
    topics: ["Hash Map", "Invariants", "Derived State"],
    blurb: "Object & System Design hub — stateful systems (mutate-and-query) and iterators (traversal contracts). Stateful System Design and Iterator Design deep dives.",
  },
  {
    cat: "theory",
    path: "theory/trees/index.html",
    nav: "Trees",
    title: "Trees",
    topics: ["Binary Tree", "BST", "Traversal", "LCA"],
    blurb: "Trees hub — tree/BST/trie vocabulary, traversal orders, and the Lowest Common Ancestor deep dive (recursive construction, post-order LCA, parent-map walk-up).",
  },
  {
    cat: "theory",
    path: "theory/graphs/index.html",
    nav: "Graphs",
    title: "Graphs",
    topics: ["BFS", "DFS", "Topological Sort", "Dijkstra"],
    blurb: "Graphs hub — vertex/edge/adjacency vocabulary, traversal families, and the BFS deep dive (grid, multi-source, state-space), DFS deep dive (components, backtracking, state DFS + memoization, cycle detection), Topological Sort deep dive (Kahn's in-degree peel, cycle detection, DAG ordering), and Dijkstra deep dive (min-heap shortest path, min-max cost, constrained/augmented state).",
  },
  // ── Walkthroughs — CUSTOM problems first, then ascending LC number order ─
  {
    cat: "walkthrough",
    path: "walkthroughs/CUSTOM1_Relay_Handoff_Coverage_master.html",
    nav: "CUSTOM 1",
    title: "CUSTOM 1 — Relay Handoff Coverage",
    topics: ["Intervals", "Prefix-Suffix", "Arrays"],
    difficulty: "M",
    blurb: "Split/handoff coverage with raw day sets (Variant 8.5). Prefix-suffix precompute reduces pair-checking from O(t²·d) to O(t·d). Covers the ≤ vs == valid-pair condition gotcha.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC3_master.html",
    nav: "LC 3",
    title: "LC 3 — Longest Substring Without Repeating Characters",
    topics: ["Sliding Window", "Hash Map", "Strings"],
    difficulty: "M",
    blurb: "Grow-and-shrink-on-invalid window (variant 8.2). The classic count-map shrink plus the last-seen-index jump optimization.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC11_master.html",
    nav: "LC 11",
    title: "LC 11 — Container With Most Water",
    topics: ["Two Pointers", "Arrays"],
    difficulty: "M",
    blurb: "Converging two pointers with min-side steering. Full proof of why moving the taller wall is provably suboptimal, with dry run and interview simulation.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC15_master.html",
    nav: "LC 15",
    title: "LC 15 — 3Sum",
    topics: ["Two Pointers", "Arrays", "Sorting"],
    difficulty: "M",
    blurb: "Converging two pointers with a fixed anchor. Two solutions compared: hashmap O(n) space vs two-pointer O(1) space — same O(n²) time, but structural skip conditions replace both Sets entirely.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC42_master.html",
    nav: "LC 42",
    title: "LC 42 — Trapping Rain Water",
    topics: ["Two Pointers", "Arrays"],
    difficulty: "H",
    blurb: "Left/right-max accumulator pattern. Commit water on the bottleneck side — the taller wall guarantees no spill. Why sliding window fails, why the two-pointer version is the O(1)-space compression of prefix-max arrays.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC125_master.html",
    nav: "LC 125",
    title: "LC 125 — Valid Palindrome",
    topics: ["Two Pointers", "Strings"],
    difficulty: "E",
    blurb: "Converging two pointers with in-place skip of non-alphanumeric characters. Single O(n) pass — no preprocessing, no cleaned copy. Covers the bounds-guard order gotcha and the Array(string) vs String.Index space tradeoff.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC56_master.html",
    nav: "LC 56",
    title: "LC 56 — Merge Intervals",
    topics: ["Intervals", "Sorting", "Arrays"],
    difficulty: "M",
    blurb: "Sort + sweep merge (Variant 8.1). The sort-once invariant that lets every step look only at result.last, the ≤ vs < overlap gotcha, and the in-place end-extension pattern.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC57_master.html",
    nav: "LC 57",
    title: "LC 57 — Insert Interval",
    topics: ["Intervals", "Arrays"],
    difficulty: "M",
    blurb: "Three-region split (Variant 8.3). The only O(n) interval variant — before / overlapping / after regions, the strict vs non-strict boundary gotcha, and the must-not-forget Region 3 tail.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC76_master.html",
    nav: "LC 76",
    title: "LC 76 — Minimum Window Substring",
    topics: ["Sliding Window", "Hash Map", "Strings"],
    difficulty: "H",
    blurb: "Shrink-while-valid sliding window with the matchedCount trick. Full interview simulation inside.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC209_master.html",
    nav: "LC 209",
    title: "LC 209 — Minimum Size Subarray Sum",
    topics: ["Sliding Window", "Arrays"],
    difficulty: "M",
    blurb: "Shrink-while-valid at its simplest — one running sum, no maps. Includes the Int.max init gotcha and full interview simulation.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC227_master.html",
    nav: "LC 227",
    title: "LC 227 — Basic Calculator II",
    topics: ["Strings", "Stack", "Parsing"],
    difficulty: "M",
    blurb: "Stack-based expression parse — deferred operator trick. Push for +/−, apply to stack top for ×/÷, flush the last operand at the final index. O(n) time, O(n) space.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC385_master.html",
    nav: "LC 385",
    title: "LC 385 — Mini Parser",
    topics: ["Strings", "Stack", "Parsing"],
    difficulty: "M",
    blurb: "Nested-structure stack parse (Variant 8.3). One scan with a stack of containers — [ descends, ] pops-and-attaches, flush-if-accumulating guards empty lists. Full Swift + dry run.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC336_master.html",
    nav: "LC 336",
    title: "LC 336 — Palindrome Pairs",
    topics: ["Strings", "Hash Map", "Palindrome"],
    difficulty: "H",
    blurb: "Reversed-prefix / palindrome matching (Variant 8.4). Index reversed words, check each word's split points for the three matching cases — beats O(w²) brute force. Full Swift + dry run.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC238_master.html",
    nav: "LC 238",
    title: "LC 238 — Product of Array Except Self",
    topics: ["Prefix-Suffix", "Arrays"],
    difficulty: "M",
    blurb: "Prefix × suffix product (Variant 8.2). Division is disqualified — zeros break it. Two passes: prefix products into the output array, then a single rolling suffix integer multiplied in right-to-left. O(n) time, O(1) extra space.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC303_master.html",
    nav: "LC 303",
    title: "LC 303 — Range Sum Query - Immutable",
    topics: ["Prefix-Suffix", "Arrays"],
    difficulty: "E",
    blurb: "Prefix sum Variant 8.1 — build once, query in O(1). The sentinel at prefix[0]=0 makes the formula prefix[right+1]−prefix[left] uniform for all ranges including those starting at index 0. O(n) init, O(1) per query.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC560_master.html",
    nav: "LC 560",
    title: "LC 560 — Subarray Sum Equals K",
    topics: ["Prefix-Suffix", "Hash Map", "Arrays"],
    difficulty: "M",
    blurb: "Prefix sum + frequency map. Negative numbers rule out sliding window. The algebraic flip — prefix[i] = currentPrefix − k — turns pair-counting into a single O(1) complement lookup per step. Sentinel {0:1} handles subarrays starting at index 0.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC759_master.html",
    nav: "LC 759",
    title: "LC 759 — Employee Free Time",
    topics: ["Intervals", "Sorting", "Arrays"],
    difficulty: "H",
    blurb: "Flatten + merge + gap-find (Variant 8.4). Free time = complement of the merged union. Recognizing the two-phase reduction is the whole problem; the gap formula and off-by-one pitfalls covered in full.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC986_master.html",
    nav: "LC 986",
    title: "LC 986 — Interval List Intersections",
    topics: ["Intervals", "Two Pointers", "Arrays"],
    difficulty: "M",
    blurb: "Two-pointer interval overlap (Variant 8.2). Walk two sorted lists simultaneously — the overlap formula, why advancing the smaller-end pointer is the only correct move, and full dry run.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC1041_master.html",
    nav: "LC 1041",
    title: "LC 1041 — Robot Bounded In Circle",
    topics: ["Strings", "Simulation", "State Machine"],
    difficulty: "M",
    blurb: "State-machine simulation — one cycle proves boundedness. Direction table + mod-4 turns + the bounded-iff-(origin-or-rotated) insight. No multi-cycle simulation needed.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC394_master.html",
    nav: "LC 394",
    title: "LC 394 — Decode String",
    topics: ["Stack", "Strings", "Parsing"],
    difficulty: "M",
    blurb: "Stack Skeleton 2 — push (count, string) context on [, pop-repeat-attach on ]. The canonical nested-structure decode: pause the outer level, build the inner, fold back. Full Swift + dry run.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC415_master.html",
    nav: "LC 415",
    title: "LC 415 — Add Strings",
    topics: ["Strings", "Simulation", "Math"],
    difficulty: "E",
    blurb: "Digit-buffer build (Variant 8.1). Right-to-left carry walk with the carry folded into the loop condition — no padding, no post-loop carry branch, append-and-reverse to stay O(n).",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC755_master.html",
    nav: "LC 755",
    title: "LC 755 — Pour Water",
    topics: ["Strings", "Simulation", "Arrays"],
    difficulty: "M",
    blurb: "Physics / grid simulation (Variant 8.3) — settle each unit by a local rule. ATTEMPT: coach-only, no solution. Settle rule, left tie-break, wall reachability, edge-case spec, graduated hints.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC68_master.html",
    nav: "LC 68",
    title: "LC 68 — Text Justification",
    topics: ["Strings", "Simulation", "Greedy"],
    difficulty: "H",
    blurb: "Greedy line-packing + space distribution (Variant 8.4). TARGET: coach-only, no solution. Two-phase frame, even/last/single-word spacing rules, the full spacing edge-case spec, graduated hints.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC348_master.html",
    nav: "LC 348",
    title: "LC 348 — Design Tic-Tac-Toe",
    topics: ["Design", "Hash Map", "Matrix"],
    difficulty: "M",
    blurb: "Incremental aggregate state (Variant 8.2). ±1 row/column/diagonal totals updated per move, win when a total hits ±n — O(1) per move, no board scan. Full Swift + dry run.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC1166_master.html",
    nav: "LC 1166",
    title: "LC 1166 — Design File System",
    topics: ["Design", "Hash Map", "Strings"],
    difficulty: "M",
    blurb: "Map-backed state (Variant 8.1). Flat [String:Int] keyed by full path, parent-exists creation rule, −1 sentinel on get — fit the representation to the operations. Full Swift + dry run.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC20_master.html",
    nav: "LC 20",
    title: "LC 20 — Valid Parentheses",
    topics: ["Stack", "Strings", "Design"],
    difficulty: "E",
    blurb: "Stack fundamentals (Variant 8.1). Push openers, pop-match closers via a closer→opener map, valid iff the stack ends empty — the LIFO mechanic every iterator reuses. Full Swift + dry run.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC341_master.html",
    nav: "LC 341",
    title: "LC 341 — Flatten Nested List Iterator",
    topics: ["Stack", "Iterator", "Design"],
    difficulty: "M",
    blurb: "Lazy stack flatten (Variant 8.2). Push the list reversed, unwind nested lists in hasNext until an integer is on top, pop in next — amortized O(1)/call, never eager. Full Swift + dry run.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC108_master.html",
    nav: "LC 108",
    title: "LC 108 — Convert Sorted Array to BST",
    topics: ["Tree", "BST", "Recursion"],
    difficulty: "E",
    blurb: "Recursive tree construction (Variant 8.1). Middle-as-root divide over index ranges builds a height-balanced BST — the recurse-and-combine reflex. Iterative frame-stack Swift + dry run.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC236_master.html",
    nav: "LC 236",
    title: "LC 236 — LCA of a Binary Tree",
    topics: ["Tree", "LCA", "Hash Map"],
    difficulty: "M",
    blurb: "Post-order LCA (Variant 8.2). Build a parent map, collect p's ancestors, walk q up to the first shared one — LCA as path intersection. Iterative Swift + recursive contrast + dry run.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC207_master.html",
    nav: "LC 207",
    title: "LC 207 — Course Schedule",
    topics: ["Topological Sort", "Graphs", "BFS"],
    difficulty: "M",
    blurb: "Topological sort via Kahn's algorithm (Variant 8.1). Model prerequisites as a directed graph, peel in-degree-0 courses, and read the cycle off the processed count — can finish iff the graph is acyclic. Full Swift + DFS three-color contrast + dry run.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC638_master.html",
    nav: "LC 638",
    title: "LC 638 — Shopping Offers",
    topics: ["DFS", "Memoization", "Top-down DP"],
    difficulty: "M",
    blurb: "DFS over the remaining-needs vector + memoization (top-down DP). The no-overshoot rule kills greedy; min(base price, each fitting offer + recurse on leftover), cached by the needs vector. Full Swift + dry run.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC1091_master.html",
    nav: "LC 1091",
    title: "LC 1091 — Shortest Path in Binary Matrix",
    topics: ["Graphs", "BFS", "Matrix"],
    difficulty: "M",
    blurb: "Grid BFS warm-up (Variant 8.1). Cells as vertices, 8-directional moves, head-index queue + visited set, distance counts cells. First arrival at the goal is the shortest path. Full Swift + dry run.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC1284_master.html",
    nav: "LC 1284",
    title: "LC 1284 — Min Flips to Convert Binary Matrix",
    topics: ["Graphs", "BFS", "Bitmask"],
    difficulty: "H",
    blurb: "State-space BFS (Variant 8.3). Encode the whole matrix as an Int bitmask, a flip is an XOR with a precomputed move-mask, BFS to state 0 gives the fewest flips. The ≤9-cell bound makes the state space tiny. Full Swift + dry run.",
  },
  {
    cat: "walkthrough",
    path: "walkthroughs/LC1631_master.html",
    nav: "LC 1631",
    title: "LC 1631 — Path With Minimum Effort",
    topics: ["Dijkstra", "Graphs", "Heap"],
    difficulty: "M",
    blurb: "Min-max Dijkstra on a grid (Variant 8.3). A path's effort is its worst step, so relax with max instead of +; a hand-rolled min-heap settles least-effort first. Full Swift (with the Heap struct) + dry run.",
  },
  {
    cat: "tips",
    path: "tips/interview_stages.html",
    nav: "Interview Stages",
    title: "Stages of an Interview",
    topics: ["Process", "Soft Skills"],
    blurb: "7-stage breakdown of a technical interview round with a condensed cheat sheet.",
  },
  {
    cat: "tips",
    path: "tips/sort_complexity.html",
    nav: "Sort Complexity",
    title: "Sorting Algorithm Complexity",
    topics: ["Complexity", "Sorting"],
    blurb: "Timsort vs Heapsort vs Counting Sort — when theory and practice diverge.",
  },
  {
    cat: "tips",
    path: "tips/cheatsheet.html",
    nav: "Big-O Cheatsheet",
    title: "Big-O & DS/A Cheatsheet",
    topics: ["Complexity", "DS&A", "Reference"],
    blurb: "Time/space complexity by data structure, input-size heuristics, and the Big-O chart.",
  },
];
